### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by b-pl** [b-pl/matchmatch#3]
**Link do skryptu**
https://github.com/b-pl/matchmatch/blob/feature/drawGRID/scripts/playGame.js

Here everything's cool. I create "div" element 16 times (cards), add class and id, append that divs to my gameBoard and add text to "divs".
https://github.com/b-pl/matchmatch/blob/8e9c7919203c7104470e9d0b522b2f4605e4cd30/scripts/playGame.js#L12-L20

And here's the problem. 
`document.querySelector('#cardID').appendChild(textnode2);  `
Throws an error

> Cannot read property 'appendChild' of null

I've tried with "replaceChild" and "innerHTML" as well. 
https://github.com/b-pl/matchmatch/blob/8e9c7919203c7104470e9d0b522b2f4605e4cd30/scripts/playGame.js#L28-L37

Any ideas how to fix it? :>

**Comment by iksemot** [comment]
The `#cardID` selector is incorrect, it should be `'#' + cardID`
